<form action="<?php echo $action; ?>" method="post">
  <div class="form-group">
    <label for="title" class="form-label">Title</label>
    <input type="text" id="title" name="title" class="form-control" value="<?php echo isset($post) ? $post['title'] : null; ?>">
  </div>
  <div class="form-group">
    <label for="content" class="form-label">Content</label>
    <textarea id="content" name="content" class="form-control"><?php echo isset($post) ? $post['content'] : null; ?></textarea>
  </div>
  <button type="submit" class="btn btn-primary">Save</button>
  <a href="/" class="btn btn-default">Back</a>
</form>
